services:
  - type: web
    name: absensi
    runtime: docker
    plan: free
    healthCheckPath: /login
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_LOCALE
        value: id
      - key: APP_TIMEZONE
        value: Asia/Jakarta
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: absensi-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: absensi-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: absensi-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: absensi-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: absensi-db
          property: password
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: FILESYSTEM_DISK
        value: public
      - key: APP_URL
        fromService:
          type: web
          name: absensi
          property: url

databases:
  - name: absensi-db
    plan: free